import Foundation

// MARK: - Settings Strings

extension Strings {
    // MARK: - Settings
    public enum Settings {
        public static let title = String(localized: "settingsTitle")
        public static let profile = String(localized: "settingsProfile")
        public static let firstDayOfWeek = String(localized: "settingsFirstDayOfWeek")
        public static let appearanceSetting = String(localized: "settingsAppearance")
        public static let followSystem = String(localized: "settingsFollowSystem")
        public static let light = String(localized: "settingsLight")
        public static let dark = String(localized: "settingsDark")
        public static let settingsSaved = String(localized: "settingsSaved")
        public static let notifications = String(localized: "settingsNotifications")
        public static let notificationPermission = String(localized: "settingsNotificationPermission")
        public static let notificationsEnabled = String(localized: "settingsNotificationsEnabled")
        public static let notificationsDisabled = String(localized: "settingsNotificationsDisabled")
        public static let enable = String(localized: "settingsEnable")
        public static let openSettings = String(localized: "settingsOpenSettings")
        public static let sectionDebug = String(localized: "settingsSectionDebug")
        public static let sectionAppearance = String(localized: "settingsSectionAppearance")
        public static let sectionTimezone = String(localized: "settingsSectionTimezone")
        public static let sectionSupport = String(localized: "settingsSectionSupport")
        public static let sectionLegal = String(localized: "settingsSectionLegal")
        public static let sectionAbout = String(localized: "settingsSectionAbout")
        public static let debugMenu = String(localized: "settingsDebugMenu")
        public static let debugMenuSubtitle = String(localized: "settingsDebugMenuSubtitle")
        public static let timezoneSettings = String(localized: "settingsTimezoneSettings")
        public static let contactSupport = String(localized: "settingsContactSupport")
        public static let helpAndFAQ = String(localized: "settingsHelpAndFAQ")
        public static let privacyPolicy = String(localized: "settingsPrivacyPolicy")
        public static let termsOfService = String(localized: "settingsTermsOfService")
        public static let version = String(localized: "settingsVersion")
        public static let build = String(localized: "settingsBuild")
        public static let acknowledgements = String(localized: "settingsAcknowledgements")
        public static let failedToLoad = String(localized: "settingsFailedToLoad")
        public static let gender = String(localized: "settingsGender")
        public static let ageGroup = String(localized: "settingsAgeGroup")
        public static let updating = String(localized: "settingsUpdating")
        public static let editProfilePicture = String(localized: "settingsEditProfilePicture")
        public static let changeAvatarHint = String(localized: "settingsChangeAvatarHint")
        public static let yourName = String(localized: "settingsYourName")
        public static let enterDisplayName = String(localized: "settingsEnterDisplayName")
        public static let genderHint = String(localized: "settingsGenderHint")
        public static let ageGroupHint = String(localized: "settingsAgeGroupHint")
        public static let personalization = String(localized: "settingsPersonalization")
        public static let demographics = String(localized: "settingsDemographics")
        public static let personalizationExplanation = String(localized: "settingsPersonalizationExplanation")
        public static let personalizationTip = String(localized: "settingsPersonalizationTip")
        public static let sectionPermissions = String(localized: "settingsSectionPermissions")
        public static let location = String(localized: "settingsLocation")
        public static let requestNotificationPermission = String(localized: "settingsRequestNotificationPermission")
        public static let enableNotificationsHint = String(localized: "settingsEnableNotificationsHint")
        public static let openNotificationSettings = String(localized: "settingsOpenNotificationSettings")
        public static let opensSettingsApp = String(localized: "settingsOpensSettingsApp")
        public static let requestLocationPermission = String(localized: "settingsRequestLocationPermission")
        public static let enableLocationHint = String(localized: "settingsEnableLocationHint")
        public static let openLocationSettings = String(localized: "settingsOpenLocationSettings")
        public static let sectionConnectWithUs = String(localized: "settingsSectionConnectWithUs")
        public static let instagram = String(localized: "settingsInstagram")
        public static let xTwitter = String(localized: "settingsXTwitter")
        public static let tiktok = String(localized: "settingsTikTok")
        public static let visitWebsite = String(localized: "settingsVisitWebsite")
        public static let acknowledgementsIntro = String(localized: "settingsAcknowledgementsIntro")
        public static let factoryDescription = String(localized: "settingsFactoryDescription")
        public static let viewOnGitHub = String(localized: "settingsViewOnGitHub")
        public static let appSettings = String(localized: "settingsAppSettings")
        public static let sectionApp = String(localized: "settingsSectionApp")
        public static let sectionSettings = String(localized: "settingsSectionSettings")
        public static let sectionFeedback = String(localized: "settingsSectionFeedback")
        public static let sectionIconVisibility = String(localized: "settingsSectionIconVisibility")
        public static let iconVisibilityFooter = String(localized: "settingsIconVisibilityFooter")
        public static let showTimeReminderIcon = String(localized: "settingsShowTimeReminderIcon")
        public static let showLocationIcon = String(localized: "settingsShowLocationIcon")
        public static let showScheduleIcon = String(localized: "settingsShowScheduleIcon")
        public static let showStreakAtRiskIcon = String(localized: "settingsShowStreakAtRiskIcon")
        public static let hapticFeedback = String(localized: "settingsHapticFeedback")
        public static let hapticFeedbackDescription = String(localized: "settingsHapticFeedbackDescription")
        public static let hapticFeedbackFooter = String(localized: "settingsHapticFeedbackFooter")
    }

    // MARK: - Timezone Settings
    public enum Timezone {
        public static let title = String(localized: "timezoneTitle")
        public static let intro = String(localized: "timezoneIntro")
        public static let errorTitle = String(localized: "timezoneErrorTitle")
        public static let failedToUpdateMode = String(localized: "timezoneFailedToUpdateMode")
        public static let failedToUpdateTimezone = String(localized: "timezoneFailedToUpdateTimezone")
        public static let youAreTraveling = String(localized: "timezoneYouAreTraveling")
        public static let travelingDescription = String(localized: "timezoneTravelingDescription")
        public static let displayMode = String(localized: "timezoneDisplayMode")
        public static let currentLocation = String(localized: "timezoneCurrentLocation")
        public static let homeLocation = String(localized: "timezoneHomeLocation")
        public static let homeTimezone = String(localized: "timezoneHomeTimezone")
        public static let habitTracking = String(localized: "timezoneHabitTracking")
        public static let habitTrackingFooter = String(localized: "timezoneHabitTrackingFooter")
        public static let timezoneInfo = String(localized: "timezoneInfo")
        public static let timezoneInfoFooter = String(localized: "timezoneInfoFooter")
        public static let currentTimezone = String(localized: "timezoneCurrentTimezone")
        public static let usingForHabits = String(localized: "timezoneUsingForHabits")
        public static func currentModeExplanation(_ timezone: String) -> String { String(format: String(localized: "timezoneCurrentModeExplanation"), timezone) }
        public static func homeModeExplanation(_ timezone: String) -> String { String(format: String(localized: "timezoneHomeModeExplanation"), timezone) }
        public static let customModeExplanation = String(localized: "timezoneCustomModeExplanation")
        public static let selectHomeTimezone = String(localized: "timezoneSelectHomeTimezone")
        public static let searchTimezones = String(localized: "timezoneSearchTimezones")
    }

    // MARK: - Timezone Change
    public enum TimezoneChange {
        public static let title = String(localized: "timezone.change.title")
        public static let keepHome = String(localized: "timezone.change.keepHome")
        public static let useCurrent = String(localized: "timezone.change.useCurrent")
        public static let movedHere = String(localized: "timezone.change.movedHere")
        public static func message(_ newTimezone: String) -> String { String(format: String(localized: "timezone.change.message"), newTimezone) }
    }
}
